# Generated by Django 2.2.4 on 2019-08-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_auto_20190825_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnprocessedRow',
        ),
    ]
