# Generated by Django 2.2.4 on 2019-08-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_delete_unprocessedrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonfile',
            name='row_count',
            field=models.IntegerField(default=10),
        ),
    ]
