# Generated by Django 2.2.4 on 2019-08-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_jsonfile_row_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonfile',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
