# Generated by Django 2.2.4 on 2019-09-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0005_jsonfile_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#FFF', max_length=20),
        ),
        migrations.AddField(
            model_name='tag',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProcessedRow',
        ),
    ]
