# Generated by Django 2.2.3 on 2019-09-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0006_auto_20190903_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
